name: "Prepare Raspbian Sysroot"
description: "Prepare a Raspbian sysroot for cross-compiling for Raspberry Pi"
branding:
  color: purple
  icon: cpu

inputs:
  sysroot:
    description: "Location of sysroot"
    default: "/opt/pi-sysroot"
    required: true
  release:
    description: "Raspbian release"
    default: "bullseye"
    required: true
  packages:
    description: "Packages to install for sysroot, can be a string or path to packages list"
    default: ""
    required: false
  basefs:
    description: "Path to cached basefs archive"
    default: /tmp/pi-debootstrap-basefs.tar.gz
    required: false

outputs:
  sysroot:
    description: "Location of sysroot"
    value: ${{ inputs.sysroot }}
  cmake-toolchain:
    description: "Path to CMake toolchain for cross compiling"
    value: ${{ inputs.sysroot }}/toolchain.cmake

runs:
  using: "composite"
  steps:
    - name: Generate Hashes
      id: hashes
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo ::set-output name=packages::$(echo "${{ inputs.packages }}" | sha256sum | head -c 64)
        echo ::set-output name=basefs::$(sha256sum basefs.sh | head -c 64)
        echo ::set-output name=sysroot::$(sha256sum sysroot.sh | head -c 64)

    - name: Cache Sysroot
      uses: actions/cache@v3
      id: cache-sysroot
      with:
        path: |
          ${{ inputs.sysroot }}/bin
          ${{ inputs.sysroot }}/lib
          ${{ inputs.sysroot }}/opt
          ${{ inputs.sysroot }}/usr
        key: sysroot-${{ inputs.release }}-${{ steps.hashes.outputs.sysroot }}-${{ steps.hashes.outputs.packages }}

    - name: Cache Base Filesystem
      if: steps.cache-sysroot.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      id: cache-basefs
      with:
        path: ${{ inputs.basefs }}
        key: basefs-${{ inputs.release }}-${{ steps.hashes.outputs.basefs }}

    - name: Update packages
      if: steps.cache-sysroot.outputs.cache-hit != 'true'
      shell: bash
      run: sudo apt-get -yq update || true

    - name: Prepare Base System
      if: steps.cache-sysroot.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ github.action_path }}
      run: sudo SYSROOT=${{ inputs.sysroot }} RELEASE=${{ inputs.release }} ARCHIVE=${{ inputs.basefs }} bash basefs.sh

    - name: Setup Sysroot
      if: steps.cache-sysroot.outputs.cache-hit != 'true'
      shell: bash
      env:
        SYSROOT: ${{ inputs.sysroot }}
        PACKAGES: ${{ inputs.packages }}
      working-directory: ${{ github.action_path }}
      run: |
        # Read packages into variable if it's a file
        if [ -f "$PACKAGES" ]; then
          PACKAGES=$(cat "$PACKAGES")
        fi
        sudo PACKAGES="$PACKAGES" chroot "$SYSROOT" /bin/bash < sysroot.sh
        sed "s|@SYSROOT@|$SYSROOT|" toolchain.cmake | sudo tee "$SYSROOT/toolchain.cmake"
