name: Build Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare Sysroot
        id: pi-sysroot
        uses: mariotaku/raspbian-sysroot-action@main
        with:
          packages: ./packages.list

      - name: Print Result
        run: |
          echo Sysroot Path: ${{ steps.pi-sysroot.outputs.sysroot }}
          echo CMake Toolchain File: ${{ steps.pi-sysroot.outputs.cmake-toolchain }}